### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by SilasK** [qiime2/q2-deblur#29]
**Questions**
Hallo,

Where exactly is the documentation. I didn't find anything on the website you have indicated.
Thank you

**Comment by wasade** [comment]
Hi @SilasK, sorry for the confusion there. Primary documentation for `Deblur` can be found [here](https://github.com/biocore/deblur). It's stubbed out in `q2-deblur` as this is how it's generally done for the qiime2 plugins right now.

**Comment by SilasK** [comment]
All the command line parameters supplied to deblur workflow are also working for q2-deblur. 

 

Why is q2 deblur not mentioned as available plug in?

 

https://docs.qiime2.org/2017.2/plugins/available/

 

Kind regards

Silas

**Comment by wasade** [comment]
It hasn't been included as part of the core distribution yet as we're constrained on developer time, but it is planned. Additionally, Deblur was just published a few weeks ago and the last q2 release was at the start of February.
