### ISSUE TITLE
Underscore sample IDs

### ISSUE THREAD

**Issue by thermokarst** [qiime2/q2-deblur#48]
Main discussion here: https://github.com/biocore/deblur/issues/157

**Comment by wasade** [comment]
Closing in favor of qiime2/qiime2#334.

The specific [line](https://github.com/qiime2/q2-deblur/blob/7d760c5734347883df0a268fc2395f8c6289a699/q2_deblur/_denoise.py#L58) of issue, though it is operating on MIENS complaint assumptions.
