### ISSUE TITLE
Expose `--left-trim-length` in plugin

### ISSUE THREAD

**Issue by ebolyen** [qiime2/q2-deblur#51]
Looks like this functionality was recently merged in Deblur: https://github.com/biocore/deblur/pull/156

**Comment by thermokarst** [comment]
This recently [came up on the forum](https://forum.qiime2.org/t/deblur-vs-dada2-questions/2093?u=thermokarst).

**Comment by efratmuller** [comment]
Is there a plan to add this feature? Or some suggested workaround?
