### ISSUE TITLE
new release 1.0.4

### ISSUE THREAD

**Issue by sjanssen2** [qiime2/q2-deblur#58]
I fixed Deblur in a way that all denoised sequences are ensured to be upper case.

As far as I understand q2, only enforces that all sequences in a biom table are upper case, thus I figure this plugin is somewhere doing the conversion to all upper cases, maybe here? https://github.com/qiime2/q2-deblur/blob/dcee4bdbc1b86910a761cd4c392591c102c8145b/q2_deblur/_denoise.py#L184

Anyways: with the new release this is fixed in the underlying Deblur program itself. From looking at the conda recipe, the new release should automatically be used when build. But you might want to document this change somewhere?
@gregcaporaso @wasade

**Comment by thermokarst** [comment]
Hi @sjanssen2!

The casing enforcement is actually dictated by [our call](https://github.com/qiime2/q2-types/blob/master/q2_types/feature_data/_transformer.py#L239-L240) into [scikit-bio](http://scikit-bio.org/docs/0.5.1/generated/skbio.sequence.DNA.html#skbio.sequence.DNA). That said, we probably want to update the [conda recipe](https://github.com/qiime2/q2-deblur/blob/master/ci/recipe/meta.yaml#L24) to reflect the new version. It wouldn't hurt to add a test or two for this situation, too. Would you be available to submit a PR for that?

**Comment by thermokarst** [comment]
Hey @wasade, would you be up for working on this during the 2018.4 release cycle? 🙏

**Comment by thermokarst** [comment]
Fixed in https://github.com/qiime2/q2-deblur/pull/60
